export { default as HomePage } from "./HomePage/HomePage.jsx";
export { default as CorporatePage } from "./CorporateAndCustom/CorporatePage.jsx";
export { default as ContactPage } from "./ContactPage/ContactPage.jsx";
export { default as AboutUsPage } from "./AboutUsPage/AboutUsPage.jsx";
export { default as HowItWorksPage } from "./HowItWorksPage/HowItWorksPage.jsx";
export { default as OurDonutsPage } from "./OurDonutsPage/OurDonutsPage.jsx";
export { default as OurLocationsPage } from "./OurLocationsPage/OurLocationsPage.jsx";
export { default as CreateOwnBoxPage } from "./CreateOwnBoxPage/CreateOwnBoxPage.jsx";
export { default as CartPage } from "./CartPage/CartPage.jsx";
